spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:../db/catalog
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect